databases:
  - name: paper-management-system_DB
    databaseName: paper_management_system_db
    user: paper-management-system
    region: Oregon

services:
  - type: web
    name: paper-management-system
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paper-management-system_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false